### ISSUE TITLE
1.6 Milestone Checklist

### ISSUE THREAD

**Issue by Kodemon** [bentojs/api-mysql#8]
- [ ] Make sure _auditor is properly handled in all queries.
 - [ ] .findById() now need to take the group as the second parameter to ensure security.
 - [ ] .find() and .findOne() should now follow the same structure for all types `where, options`

**Comment by mattgi** [comment]
default `filter` to true
